table MCN
	lineageTag: da6a03a8-763d-49cc-9e21-97223eae83cb

	column 结算日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 870ae458-8999-4601-95d6-6c34c0e92364
		summarizeBy: none
		sourceColumn: 结算日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 订单数
		dataType: int64
		formatString: 0
		lineageTag: ccc55330-83e1-4bb7-a7d8-1cff9da515c4
		summarizeBy: sum
		sourceColumn: 订单数

		annotation SummarizationSetBy = Automatic

	column 达人数
		dataType: int64
		formatString: 0
		lineageTag: 46590bc1-d17e-4184-84c0-ac92432de461
		summarizeBy: sum
		sourceColumn: 达人数

		annotation SummarizationSetBy = Automatic

	column 商品ID
		dataType: string
		lineageTag: 5938403e-9d22-48d4-90ac-4cde237f1c93
		summarizeBy: none
		sourceColumn: 商品ID

		annotation SummarizationSetBy = Automatic

	column 商品标题
		dataType: string
		lineageTag: 04f89ac9-efd1-43fd-9894-c3dbb29b204c
		summarizeBy: none
		sourceColumn: 商品标题

		annotation SummarizationSetBy = Automatic

	column 支付日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 17b991e6-6e8f-487e-960b-06e3d2245bed
		summarizeBy: none
		sourceColumn: 支付日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 订单状态
		dataType: string
		lineageTag: 24cc5d71-c42f-4891-b545-b432c922aaa2
		summarizeBy: none
		sourceColumn: 订单状态

		annotation SummarizationSetBy = Automatic

	column 计佣金额
		dataType: double
		lineageTag: 4101031f-1a14-46df-a274-3d8b91729a07
		summarizeBy: sum
		sourceColumn: 计佣金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预估机构佣金
		dataType: double
		lineageTag: 41022842-013d-4db7-8951-22c3ed63f792
		summarizeBy: sum
		sourceColumn: 预估机构佣金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 已结算机构佣金
		dataType: double
		lineageTag: 0b8999d0-613e-491d-b4b8-795b5f67145f
		summarizeBy: sum
		sourceColumn: 已结算机构佣金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 总佣金
		dataType: double
		lineageTag: 22e9273e-4b98-4c9a-aa4b-94f436300a3d
		summarizeBy: sum
		sourceColumn: 总佣金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预估技术服务费
		dataType: double
		lineageTag: ff583dd7-818d-4692-82ea-31b5724756e9
		summarizeBy: sum
		sourceColumn: 预估技术服务费

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 结算技术服务费
		dataType: double
		lineageTag: 0892c5f3-dcd6-4ad0-8116-702869661deb
		summarizeBy: sum
		sourceColumn: 结算技术服务费

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 展示名称 = 'MCN'[商品标题]&'MCN'[商品ID]
		lineageTag: b6bd2d07-2617-45c4-be0a-697d06ad4abb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition MCN = m
		mode: import
		source =
				let
				    源 = MySQL.Database(ServerName, "zhiqudb", [Query="SELECT#(lf)  DATE(FROM_UNIXTIME(a.PaySuccessTime)) AS 支付日期,#(lf)  CASE WHEN a.SettleTime = 0 THEN NULL ELSE DATE(FROM_UNIXTIME(a.SettleTime)) END AS 结算日期,#(lf)  SUM(a.PayGoodsAmount) / 100 AS 计佣金额,#(lf)  CASE a.FlowPoint#(lf)    WHEN 100 THEN '支付完成'#(lf)    WHEN 200 THEN '退款'#(lf)    WHEN 300 THEN '结算'#(lf)    WHEN 400 THEN '收货'#(lf)    ELSE '未知状态'#(lf)  END AS 订单状态,#(lf)  SUM(a.EstimatedInstitutionCommission) / 100 AS 预估机构佣金,#(lf)  SUM(a.InstitutionCommission) / 100 AS 已结算机构佣金,#(lf)  SUM(a.EstimatedTotalCommission) / 100 AS 总佣金,#(lf)  SUM(a.EstimatedTechServiceFee) / 100 AS 预估技术服务费,#(lf)  SUM(a.SettledTechServiceFee) / 100 AS 结算技术服务费,#(lf)  COUNT(DISTINCT a.OrderId) AS 订单数,#(lf)  COUNT(DISTINCT a.Yid) AS 达人数,#(lf)  a.ProductId AS 商品ID,#(lf)  p.ProductName AS 商品标题#(lf)FROM mcn.mcnorderinfo_1 a#(lf)JOIN (#(lf)  SELECT#(lf)    b.TenantId,#(lf)    b.AuthorityId,#(lf)    b.McnId,#(lf)    b.ProductId,#(lf)    COALESCE(#(lf)      MAX(CASE#(lf)            WHEN b.ProductName IS NOT NULL#(lf)             AND TRIM(b.ProductName) <> ''#(lf)             AND b.ProductName <> '名称加载中'#(lf)            THEN b.ProductName#(lf)          END),#(lf)      MAX(b.ProductName),#(lf)      '未知商品'#(lf)    ) AS ProductName#(lf)  FROM mcn.mcnorderinfo_1 b#(lf)  WHERE b.TenantId = 14#(lf)    AND b.AuthorityId = 6965018441426731278#(lf)    AND b.McnId = 6742551385696128#(lf)  GROUP BY#(lf)    b.TenantId, b.AuthorityId, b.McnId, b.ProductId#(lf)) p#(lf)  ON p.TenantId = a.TenantId#(lf) AND p.AuthorityId = a.AuthorityId#(lf) AND p.McnId = a.McnId#(lf) AND p.ProductId = a.ProductId#(lf)WHERE a.TenantId = 14#(lf)  AND a.AuthorityId = 6965018441426731278#(lf)  AND a.McnId = 6742551385696128#(lf)  AND (#(lf)    (a.PaySuccessTime >= UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH), '%Y-%m-01'))#(lf)     AND a.PaySuccessTime < UNIX_TIMESTAMP(CURDATE() + INTERVAL 1 DAY))#(lf)    OR#(lf)    (a.SettleTime >= UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH), '%Y-%m-01'))#(lf)     AND a.SettleTime < UNIX_TIMESTAMP(CURDATE() + INTERVAL 1 DAY))#(lf)  )#(lf)GROUP BY#(lf)  DATE(FROM_UNIXTIME(a.PaySuccessTime)),#(lf)  CASE WHEN a.SettleTime = 0 THEN NULL ELSE DATE(FROM_UNIXTIME(a.SettleTime)) END,#(lf)  a.ProductId,#(lf)  p.ProductName,#(lf)  CASE a.FlowPoint#(lf)    WHEN 100 THEN '支付完成'#(lf)    WHEN 200 THEN '退款'#(lf)    WHEN 300 THEN '结算'#(lf)    WHEN 400 THEN '收货'#(lf)    ELSE '未知状态'#(lf)  END#(lf)", ReturnSingleDatabase=true]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"结算日期", type date}, {"支付日期", type date}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

