table 星图提报管理
	lineageTag: 9e87eb35-aa86-4767-8fed-fa75bb4ba3fe

	column 提报日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 232115bc-9bcf-48d0-8d2f-c01facd04c6d
		summarizeBy: none
		sourceColumn: 提报日期

		variation 变体
			isDefault
			relationship: d2b3c945-6e95-4d52-908a-71b38a0ef128
			defaultHierarchy: LocalDateTable_a9041877-f697-4a46-8422-abe00907b8e5.日期层次结构

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 星图任务ID
		dataType: string
		lineageTag: a157e078-027c-4e7b-baf6-906bd2fcbb57
		summarizeBy: none
		sourceColumn: 星图任务ID

		annotation SummarizationSetBy = Automatic

	column 星图ID
		dataType: int64
		formatString: 0
		lineageTag: 9c06697c-acf0-4edf-b2c1-e25a28518555
		summarizeBy: count
		sourceColumn: 星图ID

		annotation SummarizationSetBy = Automatic

	column 品牌名称
		dataType: string
		lineageTag: b2a8a88e-96e2-46ac-b4c8-386510b142f0
		summarizeBy: none
		sourceColumn: 品牌名称

		annotation SummarizationSetBy = Automatic

	column 商单类型
		dataType: string
		lineageTag: e6725bcf-4989-464f-8a18-1f34911687ec
		summarizeBy: none
		sourceColumn: 商单类型

		annotation SummarizationSetBy = Automatic

	column 商单状态
		dataType: string
		lineageTag: 38bfd7da-bf3e-4534-b900-0f4f6b86d29a
		summarizeBy: none
		sourceColumn: 商单状态

		annotation SummarizationSetBy = Automatic

	column 提单ID
		dataType: int64
		formatString: 0
		lineageTag: 24d66782-8b17-4f1a-976c-ddd75710ef0c
		summarizeBy: count
		sourceColumn: 提单ID

		annotation SummarizationSetBy = Automatic

	column 状态
		dataType: string
		lineageTag: 0f7a98f8-0bce-4875-b5bd-48040dbce335
		summarizeBy: none
		sourceColumn: 状态

		annotation SummarizationSetBy = Automatic

	column 激活日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: df1c9078-0e39-45b0-acde-2ffaa104b3c9
		summarizeBy: none
		sourceColumn: 激活日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 完成日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e1c8aea-9745-4914-b857-826f47b04cdf
		summarizeBy: none
		sourceColumn: 完成日期

		variation 变体
			isDefault
			relationship: ad6ec117-4a73-460f-88c8-65ff6b13047e
			defaultHierarchy: LocalDateTable_cb2cb40d-be3b-4a51-a8ad-d74fbf519b34.日期层次结构

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 达人成本
		dataType: double
		lineageTag: b114a8e6-528c-4691-a1a4-5e52e9cfa556
		summarizeBy: sum
		sourceColumn: 达人成本

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 是否溢价
		dataType: int64
		formatString: 0
		lineageTag: 20cd428e-5a36-484e-a2a9-0d7895c5dc68
		summarizeBy: sum
		sourceColumn: 是否溢价

		annotation SummarizationSetBy = Automatic

	column 对客成本
		dataType: double
		lineageTag: 99663f03-16c7-4390-9086-da98a1022cba
		summarizeBy: sum
		sourceColumn: 对客成本

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 提报者ID
		dataType: int64
		formatString: 0
		lineageTag: d2369667-b74f-482d-a37b-78943074abf9
		summarizeBy: count
		sourceColumn: 提报者ID

		annotation SummarizationSetBy = Automatic

	column 提报者
		dataType: string
		lineageTag: 73f1069a-2764-4e83-97c4-f48f538dc424
		summarizeBy: none
		sourceColumn: 提报者

		annotation SummarizationSetBy = Automatic

	column 提报者所属公司
		dataType: string
		lineageTag: 7ba6ab9d-3843-4865-a180-c2b7a3c42efd
		summarizeBy: none
		sourceColumn: 提报者所属公司

		annotation SummarizationSetBy = Automatic

	column 达人内部ID
		dataType: string
		lineageTag: 17260209-c0ac-4b2a-a914-564d3bafb8c5
		summarizeBy: none
		sourceColumn: 达人内部ID

		annotation SummarizationSetBy = Automatic

	column 达人昵称
		dataType: string
		lineageTag: 0c72dad2-0985-4614-b570-7a33f974f6e4
		summarizeBy: none
		sourceColumn: 达人昵称

		annotation SummarizationSetBy = Automatic

	column 抖音号
		dataType: string
		lineageTag: 27f8178f-2a69-47e7-a9ec-59c891a93475
		summarizeBy: none
		sourceColumn: 抖音号

		annotation SummarizationSetBy = Automatic

	column 主页链接
		dataType: string
		lineageTag: f4651670-cd47-452a-bff2-3fc133b020a6
		summarizeBy: none
		sourceColumn: 主页链接

		annotation SummarizationSetBy = Automatic

	column 等级
		dataType: int64
		formatString: 0
		lineageTag: b60cca45-0d96-4880-83e2-5f71a94166d0
		summarizeBy: sum
		sourceColumn: 等级

		annotation SummarizationSetBy = Automatic

	column 粉丝数
		dataType: int64
		formatString: 0
		lineageTag: 1da7c9a0-aa2b-4deb-991a-d59c0ae0cc60
		summarizeBy: sum
		sourceColumn: 粉丝数

		annotation SummarizationSetBy = Automatic

	column 是否真人出境
		dataType: int64
		formatString: 0
		lineageTag: 2025bf12-3ea5-43b0-a758-f0fe5deb9b1e
		summarizeBy: sum
		sourceColumn: 是否真人出境

		annotation SummarizationSetBy = Automatic

	column 本部星图达人归属
		dataType: string
		lineageTag: 3fc07fed-8ba1-47e2-92bc-c62948de0aa6
		summarizeBy: none
		sourceColumn: 本部星图达人归属

		annotation SummarizationSetBy = Automatic

	column 星图达人归属
		dataType: string
		lineageTag: b781ce8b-f729-43f6-af6e-414166be79a3
		summarizeBy: none
		sourceColumn: 星图达人归属

		annotation SummarizationSetBy = Automatic

	column 关闭原因
		dataType: string
		lineageTag: 7fed2832-e3d2-4ed8-a784-6e2f5083e773
		summarizeBy: none
		sourceColumn: 关闭原因

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: int64
		formatString: 0
		lineageTag: b26c55d0-8908-4ea0-9aa0-8f55c5eed81d
		summarizeBy: sum
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition 星图提报管理 = m
		mode: import
		source =
				let
				    源 = MySQL.Database(ServerName, "zhiqudb", [Query="-- 提报管理相关数据#(lf)SELECT#(lf)    FROM_UNIXTIME(tsda.AddTime, '%Y-%m-%d') as '提报日期',#(lf)    tsd.StarDemandTaskId as ""星图任务ID"",#(lf)#(tab)#(tab)tsda.StarDemandId as ""星图ID"",#(lf)#(tab)#(tab)tsd.BrandName as ""品牌名称"",#(lf)#(tab)#(tab)CASE #(lf)        when tsd.BusinessType=1 THEN ""服务包+千川(线下)""#(lf)        when tsd.BusinessType=2 THEN ""星图+千川(线上)""#(lf)        when tsd.BusinessType=3 THEN ""星图""#(lf)    END AS '商单类型',#(lf)#(tab)#(tab)  CASE tsd.STATUS#(lf)    WHEN 0 THEN '待发布' #(lf)    WHEN 1 THEN '进行中' #(lf)    WHEN 2 THEN '已完成' #(lf)    WHEN 3 THEN '已下架' #(lf)    WHEN 4 THEN '已过期' #(lf)  END AS '商单状态',#(lf)    tsda.Id as ""提单ID"",#(lf)    tsda.`Status`,#(lf)    CASE tsda.`Status`#(lf)        WHEN 0 THEN '待审核'#(lf)        WHEN 1 THEN '商家待选'#(lf)        WHEN 2 THEN '待合作'#(lf)        WHEN 21 THEN '待提交脚本'#(lf)        WHEN 211 THEN '脚本内审'#(lf)        WHEN 22 THEN '商家审核脚本'#(lf)        WHEN 3 THEN '待提交视频'#(lf)        WHEN 31 THEN '视频内审'#(lf)        WHEN 5 THEN '商家审核视频'#(lf)        WHEN 6 THEN '待发布'#(lf)        WHEN 10 THEN '发布确认'#(lf)        WHEN 7 THEN '已完成'#(lf)        WHEN 8 THEN '已逾期'#(lf)        WHEN 9 THEN '已关闭'#(lf)        ELSE '未知状态'#(lf)    END AS ""状态"",#(lf)#(tab)#(tab)case when tsda.KolAuditTime=0 then """" else FROM_UNIXTIME(tsda.KolAuditTime, '%Y-%m-%d') end as '激活日期',  #(lf)    case when tsd.CompletedTime=0 then """" else FROM_UNIXTIME(tsd.CompletedTime, '%Y-%m-%d') end as '完成日期',#(lf)    case WHEN tsda.UseShopAmountType=1 THEN AuthKolAmount/100 ELSE tsda.KolCost/100 END as '达人成本',#(lf)#(tab)#(tab)tsda.HasPremium as '是否溢价', #(lf)    case WHEN tsda.UseShopAmountType=1 THEN AuthShopAmount/100 ELSE tsda.ShopCost/100 END as '对客成本',#(lf)#(tab)#(tab)tsda.ApplyAccountId as ""提报者ID"",#(lf)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN tsda.ApplyAccountId=0 THEN '系统'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE ai.`Name`#(lf)#(tab)#(tab)END as '提报者',#(lf)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN tsda.ApplyAccountId=0 THEN '智趣传媒'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE GROUP_CONCAT(DISTINCT NULLIF(c.Name, ''))#(lf)#(tab)#(tab)END as '提报者所属公司',#(lf)    yki.Uid as '达人内部ID',#(lf)    yki.NickName as '达人昵称',#(lf)    yki.DisplayId as '抖音号',#(lf)#(tab)#(tab)tsda.KolHomeLink as '主页链接',#(lf)#(tab)#(tab)tsda.MarketLevel as '等级',#(lf)#(tab)#(tab)tsda.FansCount as '粉丝数',#(lf)#(tab)#(tab)IsRealDisplay as '是否真人出境',#(lf)    GROUP_CONCAT(DISTINCT NULLIF(f.Name, '')) as '本部星图达人归属',#(lf)#(tab)#(tab)GROUP_CONCAT(DISTINCT NULLIF(h.Name, '')) as '星图达人归属',#(lf)CASE tsda.CloseStatus#(lf)    WHEN 0 THEN ''#(lf)    WHEN 1 THEN '提报初审未通过'#(lf)    WHEN 2 THEN '商家驳回合作'#(lf)    WHEN 3 THEN '达人确认不合作'#(lf)    WHEN 4 THEN '未下单逾期关闭'#(lf)    WHEN 5 THEN '商单关闭'#(lf)    WHEN 6 THEN '系统关闭'#(lf)    WHEN 7 THEN '商单完成'#(lf)    WHEN 8 THEN '超时未提交脚本'#(lf)    WHEN 9 THEN '超时未提交视频'#(lf)    ELSE '未知状态'  #(lf)END as '关闭原因'#(lf)FROM `tenantstardemandapply` tsda#(lf)INNER JOIN `tenantstardemand` tsd ON tsda.StarDemandId = tsd.Id #(lf)LEFT JOIN accountinfo as ai on tsda.ApplyAccountId=ai.Id#(lf)-- 达人昵称#(lf)LEFT JOIN yttkolinfo AS yki ON tsda.Yid = yki.Id#(lf)-- 本部提报者归属公司#(lf)LEFT JOIN departmentaccountmap as a on tsda.ApplyAccountId=a.AccountId#(lf)LEFT JOIN departmentinfo as b on a.DepartmentId=b.Id#(lf)LEFT JOIN company as c on b.CompanyId=c.Id#(lf)#(lf)-- 本部星图达人归属#(lf)LEFT JOIN TenantStarDemandApplyKolGroupMap as e on tsda.id=e.DemandApplyId and e.CompanyId=1#(lf)LEFT JOIN accountinfo as f on e.AccountId=f.id#(lf)-- 星图达人归属 一对多#(lf)LEFT JOIN TenantStarDemandApplyKolGroupMap as g on tsda.id=g.DemandApplyId#(lf)LEFT JOIN accountinfo as h on g.AccountId=h.id#(lf)WHERE tsda.IsDeleted = 0 AND tsd.IsDeleted = 0 and tsda.TenantId=1 and tsd.TenantId=1#(lf)#(lf)GROUP BY tsda.Id#(lf)#(lf)#(lf)#(lf)", ReturnSingleDatabase=true]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"提报日期", type date}, {"激活日期", type date}, {"完成日期", type date}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

