table 猿推库团长订单
	lineageTag: 92148558-c1d8-47d7-8e81-0543c5d3e64c

	column 商品ID
		dataType: string
		lineageTag: 93a29837-abfe-4160-b3a3-62a923757421
		summarizeBy: none
		sourceColumn: 商品ID

		annotation SummarizationSetBy = Automatic

	column 商品名称
		dataType: string
		lineageTag: 17fc0324-2ebb-47d0-b751-901388ff2617
		summarizeBy: none
		sourceColumn: 商品名称

		annotation SummarizationSetBy = Automatic

	column 结算日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 22e13a4d-8001-48d7-949d-ef7efafa086f
		summarizeBy: none
		sourceColumn: 结算日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 推广类型
		dataType: string
		lineageTag: 8001e4d0-f405-44c3-845e-8379acaa34aa
		summarizeBy: none
		sourceColumn: 推广类型

		annotation SummarizationSetBy = Automatic

	column 订单状态
		dataType: string
		lineageTag: 05ff5a32-a932-49bb-8344-2b99068c2e59
		summarizeBy: none
		sourceColumn: 订单状态

		annotation SummarizationSetBy = Automatic

	column 订单数
		dataType: double
		lineageTag: 60e5c2d8-95e6-4368-8e1c-52e2327a2a46
		summarizeBy: sum
		sourceColumn: 订单数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 达人数
		dataType: double
		lineageTag: 107e3a48-fe4a-4d61-b707-79cbaad0fd55
		summarizeBy: sum
		sourceColumn: 达人数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 总支付金额
		dataType: double
		lineageTag: 72e190f4-e33b-4426-b78c-bda9432eb6c6
		summarizeBy: sum
		sourceColumn: 总支付金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 总预估服务费收入
		dataType: double
		lineageTag: 25ac3d9e-1f96-4f0c-9557-9d6c3269eb63
		summarizeBy: sum
		sourceColumn: 总预估服务费收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 总实际服务费收入
		dataType: double
		lineageTag: 352f56e0-3ecd-4a02-ab60-79744ffab695
		summarizeBy: sum
		sourceColumn: 总实际服务费收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 支付日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 52174248-7453-43bf-9992-b213f67b2a1c
		summarizeBy: none
		sourceColumn: 支付日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 展示名称 = '猿推库团长订单'[商品名称]&'猿推库团长订单'[商品ID]
		lineageTag: 5ee6a7bf-6371-458e-bf62-5d5b5bac95f3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 猿推库团长订单 = m
		mode: import
		source =
				let
				    源 = MySQL.Database(ServerName, "zhiqudb", [Query="-- 按支付时间统计（用中间映射保证 ProductId -> 商品名称 一致）#(lf)SELECT #(lf)    DATE(FROM_UNIXTIME(a.PaySuccessTime)) AS 支付日期,#(lf)    CASE WHEN a.SettleTime = 0 THEN NULL ELSE DATE(FROM_UNIXTIME(a.SettleTime)) END AS 结算日期,#(lf)    CASE #(lf)        WHEN a.PromoterType = 1 THEN '团长'#(lf)        WHEN a.PromoterType = 2 THEN '达人'#(lf)        WHEN a.PromoterType = 3 THEN '抖客'#(lf)        ELSE '未知'#(lf)    END AS 推广类型,#(lf)    CASE a.FlowPoint#(lf)        WHEN 100 THEN '支付完成'#(lf)        WHEN 200 THEN '退款'#(lf)        WHEN 300 THEN '结算'#(lf)        WHEN 400 THEN '收货'#(lf)        ELSE '未知状态'#(lf)    END AS 订单状态,#(lf)    COUNT(DISTINCT a.OrderId) AS 订单数,#(lf)    COUNT(DISTINCT a.KolUserId) AS 达人数,#(lf)    SUM(a.PayGoodsAmount) / 100 AS 总支付金额,#(lf)    SUM(#(lf)        CASE #(lf)            WHEN a.ColonelType IN (0,1) THEN a.FirstEstimatedCommission#(lf)            WHEN a.ColonelType = 2 THEN a.SecondEstimatedCommission#(lf)            ELSE 0#(lf)        END#(lf)    ) / 100 AS 总预估服务费收入,#(lf)    SUM(#(lf)        CASE #(lf)            WHEN a.ColonelType IN (0,1) THEN a.FirstRealCommission#(lf)            WHEN a.ColonelType = 2 THEN a.SecondRealCommission#(lf)            ELSE 0#(lf)        END#(lf)    ) / 100 AS 总实际服务费收入,#(lf)    a.ProductId AS 商品ID,#(lf)    p.ProductName AS 商品名称#(lf)FROM caesar.colonelorderinfo_5 a#(lf)JOIN (#(lf)    SELECT#(lf)        b.ColonelId,#(lf)        b.ProductId,#(lf)        COALESCE(#(lf)            MAX(CASE#(lf)                    WHEN b.ProductTitle IS NOT NULL#(lf)                     AND TRIM(b.ProductTitle) <> ''#(lf)                     AND b.ProductTitle <> '名称加载中'#(lf)                    THEN b.ProductTitle#(lf)                END),#(lf)            MAX(b.ProductTitle),#(lf)            '未知商品'#(lf)        ) AS ProductName#(lf)    FROM caesar.colonelorderinfo_5 b#(lf)    WHERE b.ColonelId = 515#(lf)    GROUP BY b.ColonelId, b.ProductId#(lf)) p#(lf)    ON p.ColonelId = a.ColonelId#(lf)   AND p.ProductId = a.ProductId#(lf)WHERE a.ColonelId = 515#(lf)  AND (#(lf)      (a.PaySuccessTime >= UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH), '%Y-%m-01'))#(lf)       AND a.PaySuccessTime < UNIX_TIMESTAMP(CURDATE() + INTERVAL 1 DAY))#(lf)      OR#(lf)      (a.SettleTime >= UNIX_TIMESTAMP(DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 3 MONTH), '%Y-%m-01'))#(lf)       AND a.SettleTime < UNIX_TIMESTAMP(CURDATE() + INTERVAL 1 DAY))#(lf)  )#(lf)GROUP BY #(lf)    DATE(FROM_UNIXTIME(a.PaySuccessTime)),#(lf)    CASE WHEN a.SettleTime = 0 THEN NULL ELSE DATE(FROM_UNIXTIME(a.SettleTime)) END,#(lf)    CASE #(lf)        WHEN a.PromoterType = 1 THEN '团长'#(lf)        WHEN a.PromoterType = 2 THEN '达人'#(lf)        WHEN a.PromoterType = 3 THEN '抖客'#(lf)        ELSE '未知'#(lf)    END,#(lf)    CASE a.FlowPoint#(lf)        WHEN 100 THEN '支付完成'#(lf)        WHEN 200 THEN '退款'#(lf)        WHEN 300 THEN '结算'#(lf)        WHEN 400 THEN '收货'#(lf)        ELSE '未知状态'#(lf)    END,#(lf)    a.ProductId,#(lf)    p.ProductName;#(lf)", ReturnSingleDatabase=true]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"结算日期", type date}, {"订单数", type number}, {"达人数", type number}, {"总支付金额", type number}, {"总预估服务费收入", type number}, {"总实际服务费收入", type number}, {"支付日期", type date}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

